/**
 * Palette profiles and sprite scales (portable, no DOM).
 *
 * Two independent registries, replacing the old conflated `CONSOLES` map:
 *
 *   - PALETTE_PROFILES — the *real* hardware constraint: color palette /
 *     bit-depth / quantization mode per retro console (plus 'none' for raw
 *     passthrough).
 *   - SPRITE_SCALES — pixel footprint presets keyed by "WxH". These are
 *     game-design/zoom presets, NOT hardware facts: real games on the same
 *     console used wildly different character scales. Any "WxH" string is
 *     accepted wherever a scale key is, so persisted sizes and custom sizes
 *     keep working.
 *
 * See docs/Next-Phase.md §1 for the rationale.
 */

import {
    NES_PALETTE,
    NES_PALETTE_FLAT,
    NES_PALETTE_FULL,
} from "../nes-palette.js";

export { NES_PALETTE, NES_PALETTE_FLAT, NES_PALETTE_FULL };

// ─── Game Boy (DMG) ──────────────────────────────────────────────────────────
// The original Game Boy's LCD displayed 4 shades of green.
// Values from the classic pea-green LCD.
const gameBoyPalette = [
    [0x0f, 0x38, 0x0f], // #0f380f — darkest green
    [0x30, 0x62, 0x30], // #306230 — dark green
    [0x8b, 0xac, 0x0f], // #8bac0f — light green
    [0x9b, 0xbc, 0x0f], // #9bbc0f — lightest green
];

// ─── Sega Genesis / Mega Drive ───────────────────────────────────────────────
// 9-bit RGB: 3 bits per channel = 8 levels per channel = 512 total colors.
// Channel levels: 0, 36, 73, 109, 146, 182, 219, 255
const GENESIS_CHANNEL_LEVELS = [0, 36, 73, 109, 146, 182, 219, 255];

function generateGenesisPalette() {
    const palette = [];
    for (const r of GENESIS_CHANNEL_LEVELS) {
        for (const g of GENESIS_CHANNEL_LEVELS) {
            for (const b of GENESIS_CHANNEL_LEVELS) {
                palette.push([r, g, b]);
            }
        }
    }
    return palette; // 8 × 8 × 8 = 512 colors
}

const genesisFullPalette = generateGenesisPalette();

// ─── Commodore 64 ────────────────────────────────────────────────────────────
// Pepto palette — the most accurate C64 color reproduction.
// 16 fixed colors generated by the VIC-II chip.
const c64Palette = [
    [0, 0, 0], // 0  — Black
    [255, 255, 255], // 1  — White
    [104, 55, 43], // 2  — Red
    [112, 164, 178], // 3  — Cyan
    [111, 61, 134], // 4  — Purple
    [88, 141, 67], // 5  — Green
    [53, 40, 121], // 6  — Blue
    [184, 199, 111], // 7  — Yellow
    [111, 79, 37], // 8  — Orange
    [67, 57, 0], // 9  — Brown
    [154, 103, 89], // 10 — Light Red
    [68, 68, 68], // 11 — Dark Gray
    [108, 108, 108], // 12 — Medium Gray
    [154, 210, 132], // 13 — Light Green
    [108, 94, 181], // 14 — Light Blue
    [149, 149, 149], // 15 — Light Gray
];

// ─── Atari 2600 (NTSC TIA) ──────────────────────────────────────────────────
// 128 colors: 16 hues × 8 luminance levels.
// Based on the Stella emulator's default NTSC palette.
// Hue 0 is grayscale; hues 1–15 add chroma.
function generateAtari2600Palette() {
    const palette = [];
    const lumaLevels = [0, 37, 73, 109, 146, 182, 219, 255];

    for (let hue = 0; hue < 16; hue++) {
        for (let lum = 0; lum < 8; lum++) {
            const y = lumaLevels[lum];

            if (hue === 0) {
                palette.push([y, y, y]);
            } else {
                // NTSC TIA color generation: phase angle per hue, YIQ→RGB.
                const angle =
                    ((hue - 1) * (360 / 15) + 15) * (Math.PI / 180);
                const saturation = 50 + lum * 4;
                const i = saturation * Math.cos(angle);
                const q = saturation * Math.sin(angle);

                let r = y + 0.956 * i + 0.621 * q;
                let g = y - 0.272 * i - 0.647 * q;
                let b = y - 1.107 * i + 1.704 * q;

                r = Math.max(0, Math.min(255, Math.round(r)));
                g = Math.max(0, Math.min(255, Math.round(g)));
                b = Math.max(0, Math.min(255, Math.round(b)));

                palette.push([r, g, b]);
            }
        }
    }
    return palette; // 16 × 8 = 128 colors
}

const atariPalette = generateAtari2600Palette();

// ─── SNES 15-bit color reduction ─────────────────────────────────────────────
// The SNES uses 15-bit RGB: 5 bits per channel = 32 levels per channel.

/**
 * Reduce an [R, G, B] color to 15-bit SNES precision.
 * Each channel is quantized to 5 bits (32 levels).
 */
export function reduceTo15Bit(r, g, b) {
    const reduce = (v) => {
        const level = Math.round((v * 31) / 255); // 0–31 (5-bit value)
        return Math.round((level * 255) / 31); // back to 0–255 range
    };
    return [reduce(r), reduce(g), reduce(b)];
}

/**
 * Reduce an entire RGBA pixel array to SNES 15-bit color, in place.
 * @param {Uint8ClampedArray} pixels - RGBA pixel data
 */
export function reduceImageTo15Bit(pixels) {
    for (let i = 0; i < pixels.length; i += 4) {
        const [r, g, b] = reduceTo15Bit(pixels[i], pixels[i + 1], pixels[i + 2]);
        pixels[i] = r;
        pixels[i + 1] = g;
        pixels[i + 2] = b;
        // Alpha channel (pixels[i+3]) is left unchanged
    }
}

// ─── Palette Profiles ────────────────────────────────────────────────────────

/**
 * Registry of color profiles — the hardware-accurate half of the old
 * CONSOLES map. `defaultScale` is only a suggested starting footprint;
 * every profile works at every sprite scale.
 *
 * Each entry:
 *   - name / fullName / year / colorDepth / colorsPerSprite: display metadata
 *   - palette: Array of [R,G,B] (null if bit-depth reduction or none)
 *   - paletteFlat: Flat [R,G,B,...] for RgbQuant (null likewise)
 *   - bitDepthReduce: { bits } for per-channel reduction, or absent
 *   - quantizeMode: 'palette' | 'bitreduce' | 'none'
 *   - defaultScale: suggested SPRITE_SCALES key
 */
export const PALETTE_PROFILES = {
    none: {
        name: "None",
        fullName: "No Palette (Raw Output)",
        year: null,
        colorDepth: "Full color (24-bit)",
        colorsPerSprite: "Unlimited",
        palette: null,
        paletteFlat: null,
        quantizeMode: "none",
        defaultScale: "512x512",
    },

    nes: {
        name: "NES",
        fullName: "Nintendo Entertainment System",
        year: 1983,
        colorDepth: "6-bit (~54 colors)",
        colorsPerSprite: "3 + transparent",
        palette: NES_PALETTE,
        paletteFlat: NES_PALETTE_FLAT,
        quantizeMode: "palette",
        defaultScale: "32x32",
    },

    snes: {
        name: "SNES",
        fullName: "Super Nintendo",
        year: 1990,
        colorDepth: "15-bit (32,768 colors)",
        colorsPerSprite: "15 + transparent",
        palette: null,
        paletteFlat: null,
        bitDepthReduce: { bits: 5 },
        quantizeMode: "bitreduce",
        defaultScale: "32x32",
    },

    genesis: {
        name: "Genesis",
        fullName: "Sega Genesis / Mega Drive",
        year: 1988,
        colorDepth: "9-bit (512 colors)",
        colorsPerSprite: "15 + transparent",
        palette: genesisFullPalette,
        paletteFlat: genesisFullPalette.flat(),
        quantizeMode: "palette",
        defaultScale: "32x32",
    },

    gameboy: {
        name: "Game Boy",
        fullName: "Nintendo Game Boy",
        year: 1989,
        colorDepth: "2-bit (4 shades)",
        colorsPerSprite: "3 + transparent",
        palette: gameBoyPalette,
        paletteFlat: gameBoyPalette.flat(),
        quantizeMode: "palette",
        defaultScale: "16x16",
    },

    c64: {
        name: "C64",
        fullName: "Commodore 64",
        year: 1982,
        colorDepth: "4-bit (16 fixed colors)",
        colorsPerSprite: "1-3 + background",
        palette: c64Palette,
        paletteFlat: c64Palette.flat(),
        quantizeMode: "palette",
        defaultScale: "24x24",
    },

    atari: {
        name: "Atari 2600",
        fullName: "Atari Video Computer System",
        year: 1977,
        colorDepth: "7-bit (128 colors)",
        colorsPerSprite: "1 + background",
        palette: atariPalette,
        paletteFlat: atariPalette.flat(),
        quantizeMode: "palette",
        defaultScale: "16x16",
    },
};

/** Default palette profile selection */
export const DEFAULT_PROFILE = "nes";

// ─── Sprite Scales ───────────────────────────────────────────────────────────

/**
 * Footprint presets keyed by "WxH". Labels name the *intent* (genre/zoom),
 * because these were never hardware constraints. Any other "WxH" string is
 * also accepted by parseSpriteSize, so custom and previously-persisted
 * sizes keep working.
 */
export const SPRITE_SCALES = {
    "8x8": { w: 8, h: 8, label: "Micro" },
    "16x16": { w: 16, h: 16, label: "Tiny" },
    "24x24": { w: 24, h: 24, label: "Small" },
    "32x32": { w: 32, h: 32, label: "Classic" },
    "48x48": { w: 48, h: 48, label: "Detailed" },
    "64x64": { w: 64, h: 64, label: "HD" },
    "96x96": { w: 96, h: 96, label: "Large" },
    "128x128": { w: 128, h: 128, label: "XL" },
    "256x256": { w: 256, h: 256, label: "Huge" },
    "512x512": { w: 512, h: 512, label: "Raw" },
};

/**
 * Resolve a scale key or arbitrary "WxH" string to pixel dimensions.
 * @param {string} sizeKey - e.g. "32x32", "24x21" (custom), "8x16"
 * @returns {{ w: number, h: number }}
 * @throws {Error} If the string is not a preset key or parseable "WxH"
 */
export function parseSpriteSize(sizeKey) {
    const preset = SPRITE_SCALES[sizeKey];
    if (preset) return { w: preset.w, h: preset.h };

    const match = /^(\d+)x(\d+)$/.exec(String(sizeKey).trim());
    if (match) {
        const w = parseInt(match[1], 10);
        const h = parseInt(match[2], 10);
        if (w > 0 && h > 0 && w <= 1024 && h <= 1024) return { w, h };
    }
    throw new Error(
        `Unknown sprite size "${sizeKey}". Use a preset (${Object.keys(SPRITE_SCALES).join(", ")}) or a custom "WxH" up to 1024.`,
    );
}

// ─── Helper Functions ────────────────────────────────────────────────────────

/**
 * Get a palette profile by id.
 * @param {string} profileId - Key from PALETTE_PROFILES (e.g. 'nes')
 * @throws {Error} If profileId is not found
 */
export function getPaletteProfile(profileId) {
    const entry = PALETTE_PROFILES[profileId];
    if (!entry) {
        throw new Error(
            `Unknown palette profile: "${profileId}". Valid options: ${Object.keys(PALETTE_PROFILES).join(", ")}`,
        );
    }
    return entry;
}
