/**
 * Multi-Console Palette Module
 *
 * Provides accurate color palettes for retro gaming consoles:
 *   - NES (Nintendo Entertainment System)
 *   - SNES (Super Nintendo)
 *   - Sega Genesis / Mega Drive
 *   - Game Boy (DMG)
 *   - Commodore 64
 *   - Atari 2600
 *
 * Each console entry includes palette data, sprite sizes, and
 * metadata describing the console's color capabilities.
 */

// ─── Re-export NES palette for backward compatibility ────────────────────────
export { NES_PALETTE, NES_PALETTE_FLAT, NES_PALETTE_FULL } from './nes-palette.js';

import { NES_PALETTE, NES_PALETTE_FLAT } from './nes-palette.js';

// ─── Game Boy (DMG) ──────────────────────────────────────────────────────────
// The original Game Boy's LCD displayed 4 shades of green.
// Values from the classic pea-green LCD.
const gameBoyPalette = [
  [0x0f, 0x38, 0x0f],  // #0f380f — darkest green
  [0x30, 0x62, 0x30],  // #306230 — dark green
  [0x8b, 0xac, 0x0f],  // #8bac0f — light green
  [0x9b, 0xbc, 0x0f],  // #9bbc0f — lightest green
];

// ─── Sega Genesis / Mega Drive ───────────────────────────────────────────────
// 9-bit RGB: 3 bits per channel = 8 levels per channel = 512 total colors.
// Channel levels: 0, 36, 73, 109, 146, 182, 219, 255
const GENESIS_CHANNEL_LEVELS = [0, 36, 73, 109, 146, 182, 219, 255];

function generateGenesisPalette() {
  const palette = [];
  for (const r of GENESIS_CHANNEL_LEVELS) {
    for (const g of GENESIS_CHANNEL_LEVELS) {
      for (const b of GENESIS_CHANNEL_LEVELS) {
        palette.push([r, g, b]);
      }
    }
  }
  return palette; // 8 × 8 × 8 = 512 colors
}

const genesisFullPalette = generateGenesisPalette();

// ─── Commodore 64 ────────────────────────────────────────────────────────────
// Pepto palette — the most accurate C64 color reproduction.
// 16 fixed colors generated by the VIC-II chip.
const c64Palette = [
  [  0,   0,   0],  // 0  — Black
  [255, 255, 255],  // 1  — White
  [104,  55,  43],  // 2  — Red
  [112, 164, 178],  // 3  — Cyan
  [111,  61, 134],  // 4  — Purple
  [ 88, 141,  67],  // 5  — Green
  [ 53,  40, 121],  // 6  — Blue
  [184, 199, 111],  // 7  — Yellow
  [111,  79,  37],  // 8  — Orange
  [ 67,  57,   0],  // 9  — Brown
  [154, 103,  89],  // 10 — Light Red
  [ 68,  68,  68],  // 11 — Dark Gray
  [108, 108, 108],  // 12 — Medium Gray
  [154, 210, 132],  // 13 — Light Green
  [108,  94, 181],  // 14 — Light Blue
  [149, 149, 149],  // 15 — Light Gray
];

// ─── Atari 2600 (NTSC TIA) ──────────────────────────────────────────────────
// 128 colors: 16 hues × 8 luminance levels.
// Based on the Stella emulator's default NTSC palette.
// Hue 0 is grayscale; hues 1–15 add chroma.
//
// Generated using the standard NTSC TIA color generation approximation:
//   For hue 0 (grayscale): R = G = B = luma
//   For hues 1–15: phase angle = (hue - 1) * (360/15), apply YIQ-to-RGB
function generateAtari2600Palette() {
  const palette = [];
  // 8 luminance levels evenly spaced from ~0 to ~255
  const lumaLevels = [0, 37, 73, 109, 146, 182, 219, 255];

  for (let hue = 0; hue < 16; hue++) {
    for (let lum = 0; lum < 8; lum++) {
      const y = lumaLevels[lum];

      if (hue === 0) {
        // Grayscale
        palette.push([y, y, y]);
      } else {
        // NTSC TIA color generation:
        // Phase angle for each hue (15 chromatic hues spread across 360°)
        // The TIA's color burst reference is ~180°; hue 1 starts near gold/orange.
        const angle = ((hue - 1) * (360 / 15) + 15) * (Math.PI / 180);

        // Chrominance amplitude scales with luminance (brighter = more saturated),
        // but we use a fixed saturation for the standard palette look.
        const saturation = 50 + lum * 4;

        // YIQ to RGB conversion (NTSC standard)
        const i = saturation * Math.cos(angle);
        const q = saturation * Math.sin(angle);

        let r = y + 0.956 * i + 0.621 * q;
        let g = y - 0.272 * i - 0.647 * q;
        let b = y - 1.107 * i + 1.704 * q;

        // Clamp to [0, 255]
        r = Math.max(0, Math.min(255, Math.round(r)));
        g = Math.max(0, Math.min(255, Math.round(g)));
        b = Math.max(0, Math.min(255, Math.round(b)));

        palette.push([r, g, b]);
      }
    }
  }
  return palette; // 16 × 8 = 128 colors
}

const atariPalette = generateAtari2600Palette();

// ─── SNES 15-bit color reduction ─────────────────────────────────────────────
// The SNES uses 15-bit RGB: 5 bits per channel = 32 levels per channel.
// Rather than a fixed palette of 32,768 colors, we reduce each channel
// to 5-bit precision by rounding to the nearest multiple of 8 (0–248),
// then scaling back to 0–255.
//
// 5-bit values: 0, 8, 16, ..., 248 → mapped to 0, 8, 16, ..., 248
// More precisely: value = round(channel / 8) * 8, clamped to [0, 248]

/**
 * Reduce an [R, G, B] color to 15-bit SNES precision.
 * Each channel is quantized to 5 bits (32 levels).
 * @param {number} r - Red channel (0–255)
 * @param {number} g - Green channel (0–255)
 * @param {number} b - Blue channel (0–255)
 * @returns {number[]} - [R, G, B] quantized to 5-bit per channel
 */
export function reduceTo15Bit(r, g, b) {
  // Quantize each channel: round to nearest 5-bit level, then scale to 8-bit
  // 5-bit has 31 max value, each step = 255/31 ≈ 8.226
  const reduce = (v) => {
    const level = Math.round(v * 31 / 255);         // 0–31 (5-bit value)
    return Math.round(level * 255 / 31);             // back to 0–255 range
  };
  return [reduce(r), reduce(g), reduce(b)];
}

/**
 * Reduce an entire ImageData (or pixel array) to SNES 15-bit color.
 * Modifies the array in place.
 * @param {Uint8ClampedArray} pixels - RGBA pixel data
 */
export function reduceImageTo15Bit(pixels) {
  for (let i = 0; i < pixels.length; i += 4) {
    const [r, g, b] = reduceTo15Bit(pixels[i], pixels[i + 1], pixels[i + 2]);
    pixels[i] = r;
    pixels[i + 1] = g;
    pixels[i + 2] = b;
    // Alpha channel (pixels[i+3]) is left unchanged
  }
}

// ─── Unified Console Registry ────────────────────────────────────────────────

/**
 * Registry of retro console palette configurations.
 *
 * Each entry contains:
 *   - name / fullName / year: display metadata
 *   - colorDepth: human-readable description
 *   - colorsPerSprite: hardware sprite color limit
 *   - palette: Array of [R,G,B] triplets (null if using bit-depth reduction)
 *   - paletteFlat: Flat [R,G,B,R,G,B,...] for RgbQuant (null if using reduction)
 *   - bitDepthReduce: if non-null, { bits } for per-channel bit reduction
 *   - spriteSizes: available sprite dimensions
 *   - defaultSize: default sprite size key
 *   - quantizeMode: 'palette' (fixed palette) or 'bitreduce' (per-channel reduction)
 */
export const CONSOLES = {
  nes: {
    name: 'NES',
    fullName: 'Nintendo Entertainment System',
    year: 1983,
    colorDepth: '6-bit (~54 colors)',
    colorsPerSprite: '3 + transparent',
    palette: NES_PALETTE,
    paletteFlat: NES_PALETTE_FLAT,
    spriteSizes: {
      '8x8':  { w: 8,  h: 8 },
      '8x16': { w: 8,  h: 16 },
      '16x16': { w: 16, h: 16 },
      '32x32': { w: 32, h: 32 },
    },
    defaultSize: '16x16',
    quantizeMode: 'palette',
  },

  snes: {
    name: 'SNES',
    fullName: 'Super Nintendo',
    year: 1990,
    colorDepth: '15-bit (32,768 colors)',
    colorsPerSprite: '15 + transparent',
    palette: null,
    paletteFlat: null,
    bitDepthReduce: { bits: 5 },
    spriteSizes: {
      '8x8':   { w: 8,  h: 8 },
      '16x16': { w: 16, h: 16 },
      '32x32': { w: 32, h: 32 },
      '64x64': { w: 64, h: 64 },
    },
    defaultSize: '32x32',
    quantizeMode: 'bitreduce',
  },

  genesis: {
    name: 'Genesis',
    fullName: 'Sega Genesis / Mega Drive',
    year: 1988,
    colorDepth: '9-bit (512 colors)',
    colorsPerSprite: '15 + transparent',
    palette: genesisFullPalette,
    paletteFlat: genesisFullPalette.flat(),
    spriteSizes: {
      '8x8':   { w: 8,  h: 8 },
      '16x16': { w: 16, h: 16 },
      '32x32': { w: 32, h: 32 },
    },
    defaultSize: '16x16',
    quantizeMode: 'palette',
  },

  gameboy: {
    name: 'Game Boy',
    fullName: 'Nintendo Game Boy',
    year: 1989,
    colorDepth: '2-bit (4 shades)',
    colorsPerSprite: '3 + transparent',
    palette: gameBoyPalette,
    paletteFlat: gameBoyPalette.flat(),
    spriteSizes: {
      '8x8':   { w: 8,  h: 8 },
      '8x16':  { w: 8,  h: 16 },
      '16x16': { w: 16, h: 16 },
    },
    defaultSize: '16x16',
    quantizeMode: 'palette',
  },

  c64: {
    name: 'C64',
    fullName: 'Commodore 64',
    year: 1982,
    colorDepth: '4-bit (16 fixed colors)',
    colorsPerSprite: '1-3 + background',
    palette: c64Palette,
    paletteFlat: c64Palette.flat(),
    spriteSizes: {
      '12x21': { w: 12, h: 21 },
      '24x21': { w: 24, h: 21 },
      '16x16': { w: 16, h: 16 },
    },
    defaultSize: '16x16',
    quantizeMode: 'palette',
  },

  atari: {
    name: 'Atari 2600',
    fullName: 'Atari Video Computer System',
    year: 1977,
    colorDepth: '7-bit (128 colors)',
    colorsPerSprite: '1 + background',
    palette: atariPalette,
    paletteFlat: atariPalette.flat(),
    spriteSizes: {
      '8x8':  { w: 8,  h: 8 },
      '8x16': { w: 8,  h: 16 },
      '16x16': { w: 16, h: 16 },
    },
    defaultSize: '8x16',
    quantizeMode: 'palette',
  },
};

/** Default console selection */
export const DEFAULT_CONSOLE = 'nes';

// ─── Helper Functions ────────────────────────────────────────────────────────

/**
 * Get the available sprite sizes for a console.
 * @param {string} consoleId - Key from CONSOLES (e.g. 'nes', 'snes')
 * @returns {Object} Map of size keys to {w, h} objects
 * @throws {Error} If consoleId is not found
 */
export function getSpriteSizesForConsole(consoleId) {
  const entry = CONSOLES[consoleId];
  if (!entry) {
    throw new Error(`Unknown console: "${consoleId}". Valid options: ${Object.keys(CONSOLES).join(', ')}`);
  }
  return entry.spriteSizes;
}

/**
 * Get the palette configuration for a console.
 * @param {string} consoleId - Key from CONSOLES (e.g. 'nes', 'genesis')
 * @returns {{ palette: number[][]|null, paletteFlat: number[]|null, quantizeMode: string, bitDepthReduce: Object|undefined }}
 * @throws {Error} If consoleId is not found
 */
export function getPaletteForConsole(consoleId) {
  const entry = CONSOLES[consoleId];
  if (!entry) {
    throw new Error(`Unknown console: "${consoleId}". Valid options: ${Object.keys(CONSOLES).join(', ')}`);
  }
  return {
    palette: entry.palette,
    paletteFlat: entry.paletteFlat,
    quantizeMode: entry.quantizeMode,
    bitDepthReduce: entry.bitDepthReduce || null,
  };
}
